### ISSUE TITLE
Archiving on CRAN

### ISSUE THREAD

**Issue by ellessenne** [kkholst/mets#3]
Hi, 
I am the maintainer of the {KMunicate} package, which depends on {pammtools}, which depends on {pec}, which depends on {riskRegression}, which (finally!) depends on {mets}. I have been given notice by CRAN maintainers that the package will be archived on 2022-10-06 unless [the issues with these checks](https://cran.r-project.org/web/checks/check_results_mets.html) are addressed by then.
I thought about reporting this here as well, just in case, is there any update/timeline on that?
Thanks!

Alessandro

**Comment by klaus-holst** [comment]
Hi Alessandro,

I am aware of the issues and working on a new release which I plan to submit to CRAN before the end of this week.

Best regards,
Klaus

**Comment by ellessenne** [comment]
Hi @klaus-holst, 
That's great to hear, thanks very much!
Best wishes,

Alessandro
